#pragma once

#include "TableCrcSDevice/Crc8/public.h"

#define IS_VALID_THIS_HANDLE(handle) SDEVICE_IS_VALID_HANDLE(TableCrc8, handle)

SDEVICE_RUNTIME_DATA_FORWARD_DECLARATION(TableCrc8);

SDEVICE_RUNTIME_DATA_DECLARATION(TableCrc8)
{
   const uint8_t *LookupTable;
};

SDEVICE_HANDLE_DECLARATION(TableCrc8);
SDEVICE_INTERNAL_ALIASES_DECLARATION(TableCrc8);
